---
- hosts: all
  vars:
    ci_config_repo: "{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/config'].src_dir }}"
    ovb_repo_source_dir: "{{ ansible_user_dir }}/{{ zuul.projects['git.openstack.org/openstack/openstack-virtual-baremetal'].src_dir }}"
    ovb_clone: false
    workspace: "{{ ansible_user_dir }}/workspace"
  tasks:

    - name: set collection timeout
      set_fact:
        collect_timeout_sec: "{{ zuul.post_timeout|default(3600) -  copy_logs_time|default(300) }}"

    - name: Collect logs from OVB before deleting nodes
      shell: >
        timeout --preserve-status -s 15
          -k {{ [collect_timeout_sec|int, 60]|sum|string }} {{ collect_timeout_sec|string }}
          bash {{ workspace }}/logs/collect_logs.sh;
        mv {{ workspace }}/logs/collect_logs.sh {{ workspace }}/logs/ovb_collect_logs.sh;

    - name: Delete OVB environment
      include_role:
        name: ovb-manage
      vars:
        ovb_manage_stack_mode: delete
        ovb_working_dir: "{{ workspace }}/ovb"
        logs_dir: "{{ workspace }}/logs"
      when: remove_ovb_after_job|default(true)|bool
