resources:
  groups:
    config-core:
      description: Core developers for project config
      members:
      - alan.pevec@redhat.com
      - fboucher@redhat.com
      - flepied@redhat.com
      - gcerami@redhat.com
      - jpena@redhat.com
      - jruzicka@redhat.com
      - mhuin@redhat.com
      - nhicher@redhat.com
      - rlandy@redhat.com
      - sshnaidm@redhat.com
      - zcaplovi@redhat.com
      - marios@redhat.com
      - ssbarnea@redhat.com
    config-ptl:
      description: Project team lead for project config
      members:
      - dms@redhat.com
      - admin@review.rdoproject.org
      - tdecacqu@redhat.com
