resources:
  groups:
    config-core:
      description: Core developers for project config
      members:
      - alan.pevec@redhat.com
      - pawlik.dan@gmail.com
      - fboucher@redhat.com
      - mhuin@redhat.com
      - nhicher@redhat.com
      - chkumar@redhat.com
      - cjeanner+github@redhat.com
      - marios@redhat.com
      - rlandy@redhat.com
      - sandyada@redhat.com
      - viroel@gmail.com
      - fserucas@redhat.com
      - tino.calancha@gmail.com
    config-ptl:
      description: Project team lead for project config
      members:
      - admin@review.rdoproject.org
      - tdecacqu@redhat.com
