- hosts: all
  vars:
    workspace: "{{ ansible_user_dir }}/workspace"
    ci_config_repo: "{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/config'].src_dir }}"
    images_working_dir: "{{ ansible_user_dir }}/workspace"
  tasks:

    - block:

      - name: Create image tars
        archive:
          path: "{{ image_files_to_tar }}"
          dest: "{{ images_working_dir }}/{{ image_tar_file }}.tar"
          format: tar

      - name: Create md5sums
        shell: |
          md5sum {{ image_tar_file }}.tar > {{ image_tar_file }}.tar.md5
        args:
          chdir: "{{ images_working_dir }}"

      - name: Create SSH private key tempfile
        tempfile:
          state: file
        register: ssh_private_key_tmp

      - name: Create SSH private key from secret
        copy:
          content: >-
            {% if ansible_distribution|lower == 'redhat' -%}
            "{{ site_logs.ssh_private_key }}"
            {%- else -%}
            "{{ uploader_ssh_key.ssh_private_key }}"
            {%- endif %}
          dest: "{{ ssh_private_key_tmp.path }}"
          mode: 0600

      - name: Upload image
        shell:
          cmd: |
            eval "$(ssh-agent)"
            ssh-add {{ ssh_private_key_tmp.path }}
            shred {{ ssh_private_key_tmp.path }}
            export RELEASE={{ release }}
            export DISTRO_NAME="{{ ansible_distribution|lower }}"
            export DISTRO_VERSION="{{ ansible_distribution_major_version }}"
            mkdir -p {{ workspace }}/logs/images-upload/
            bash -xe {{ ci_config_repo }}/ci-scripts/tripleo-upstream/convert-upload-undercloud.sh
            bash -xe {{ ci_config_repo }}/ci-scripts/tripleo-upstream/upload-cloud-images.sh
            echo export UPLOAD_EXIT_VALUE=$? >> {{ workspace }}/hash_info.sh
            cp $HOME/*repo_setup*log {{ workspace }}/logs/images-upload || true
          chdir: '{{ ansible_user_dir }}/workspace'
        environment: '{{ zuul | zuul_legacy_vars }}'

      always:
        - name: Kill ssh-agent
          command: "pkill ssh-agent"

      when: zuul_success|bool
