- hosts: primary:tripleo-ovb-centos-7
  tasks:
    - shell:
        cmd: |
          source $WORKSPACE/hash_info.sh
          export TOCI_JOBTYPE="{{ toci_jobtype }}"
          export SUCCESS="{{ zuul_success | bool }}"
          bash -xe $WORKSPACE/rdo-infra/ci-config/ci-scripts/tripleo-upstream/dlrnapi_report.sh
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: "{{ zuul | zuul_legacy_vars | combine({'DLRNAPI_PASSWORD': dlrnapi.password}) }}"
