- hosts: primary:tripleo-ovb-centos-7
  tasks:
    - name: Set zuul-log-path fact
      include_role:
        name: set-zuul-log-path-fact
    - shell:
        cmd: |
          export RELEASE={{ release }}
          export TOCI_JOBTYPE="{{ toci_jobtype }}"
          export LOG_PATH="{{ zuul_log_path }}"
          export SUCCESS="{{ zuul_success | bool }}"
          bash -xe $WORKSPACE/rdo-infra/ci-config/ci-scripts/tripleo-upstream/dlrnapi_report.sh
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: "{{ zuul | zuul_legacy_vars | combine({'DLRNAPI_PASSWORD': dlrnapi.password}) }}"
